spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cyberedge_db
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Options: update | create | create-drop | validate | none
    show-sql: true  # Set to false in production
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true  # Required for PostgreSQL

  sql:
    init:
      mode: always  # Set to "never" to disable automatic schema initialization

